"""Add created_at field to User model

Revision ID: 123fcd90fadb
Revises: 2c30fcf59392
Create Date: 2025-04-11 01:52:50.049544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123fcd90fadb'
down_revision = '2c30fcf59392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
