"""Add medical expert fields and relationships

Revision ID: 95ccd2e36194
Revises: 123fcd90fadb
Create Date: 2025-04-11 22:29:14.655448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95ccd2e36194'
down_revision = '123fcd90fadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_reviewed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('needs_attention', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('expert_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.alter_column('confidence',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['reviewed_by'], ['id'])
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('license_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_approved')
        batch_op.drop_column('license_number')
        batch_op.drop_column('specialization')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('confidence',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('expert_notes')
        batch_op.drop_column('needs_attention')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('is_reviewed')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
